"""add hashed_password to users

Revision ID: 35c76037ae5e
Revises: 5656ed87d564
Create Date: 2026-03-18 22:43:09.786640

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '35c76037ae5e'
down_revision: Union[str, None] = '5656ed87d564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
