"""add interview history

Revision ID: 6c1820772ff1
Revises: 35c76037ae5e
Create Date: 2026-03-18 23:22:25.916274

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6c1820772ff1'
down_revision: Union[str, None] = '35c76037ae5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('round_type', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('communication_score', sa.Integer(), nullable=True),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_history')),
    sa.UniqueConstraint('session_id', name=op.f('uq_interview_history_session_id'))
    )
    op.create_index(op.f('ix_interview_history_user_id'), 'interview_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_history_user_id'), table_name='interview_history')
    op.drop_table('interview_history')
    # ### end Alembic commands ###
